### PR TITLE
Pull request from sofia_csy branch

### PR DESCRIPTION
**Pull request by rth**
@jacksoncsy It looks like you did some interesting development in the `sofia_csy` branch, particularly with respect to removing temporary files,  wrapping  a few more core methods with Cython and generalizing the train function. I was wondering what if it would be possible to merge this into the `master` branch, or what would be necessary to make it happen. I guess a few suggestions could be: 
-  removing or renaming to something more verbose the `examples/my_*ipynb`
-  possibly adding `examples/.ipynb_checkpoints` to `.gitignore` and remove it from the commit
-  possibly  incrementing the pysofia version number (if it exists) as there are probably some  backward incompatible changes. 

@fabianp  I'm not sure if this would break things currently based on the version in master. 
I would like to do some small contributions of my own (e.g. adding PY2/PY3 compatibility, etc) and was thinking to start from the `sofia_csy` branch, so I just wanted to make sure that it could be potentially merged back at some point. Thanks.

### CODE REVIEW

**Comment by fabianp** [comment]
I don't have time to review in detail but overall looks like an improvement. Merging

**Comment by fabianp** [comment]
Thanks!

**Comment by jacksoncsy** [comment]
Hi Guys,

Sorry, I am not regular user of Github! I just saw your posts, thanks for looking at my commits!
Please feel free to merge anything useful, I am totally ok with that!

Cheers,
Shiyang

**Comment by rth** [comment]
@jacksoncsy No problem, thanks for contributing! Cheers

**Pull request merged**
